// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_clean_tdd/test/features/number_trivia/presentation/cubit/number_trivia_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i5;
import 'package:flutter_clean_tdd/features/core/error/failures.dart' as _i6;
import 'package:flutter_clean_tdd/features/core/usecase/usecase.dart' as _i8;
import 'package:flutter_clean_tdd/features/number_trivia/domain/entities/number_trivia.dart'
    as _i7;
import 'package:flutter_clean_tdd/features/number_trivia/domain/repositories/number_trivia_repo.dart'
    as _i2;
import 'package:flutter_clean_tdd/features/number_trivia/domain/usecases/get_concrete_number_trivia.dart'
    as _i3;
import 'package:flutter_clean_tdd/features/number_trivia/domain/usecases/get_random_number_trivia.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNumberTriviaRepository_0 extends _i1.SmartFake
    implements _i2.NumberTriviaRepository {
  _FakeNumberTriviaRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetConcreteNumberTrivia].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcreteNumberTrivia extends _i1.Mock
    implements _i3.GetConcreteNumberTrivia {
  MockGetConcreteNumberTrivia() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumberTriviaRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeNumberTriviaRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.NumberTriviaRepository);
  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?> call(
          _i8.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?>.value(),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?>);
}

/// A class which mocks [GetRandomNumberTrivia].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomNumberTrivia extends _i1.Mock
    implements _i9.GetRandomNumberTrivia {
  MockGetRandomNumberTrivia() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumberTriviaRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeNumberTriviaRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.NumberTriviaRepository);
  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?>.value(),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.NumberTrivia>?>);
}
